name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  internet_connection_checker: ^1.0.0 # Add this

  # Functional programming helpers (Either, Left, Right)
  dartz: ^0.10.1

  # Value comparison for entities/models
  equatable: ^2.0.5

  shared_preferences: ^2.2.3 # Add this
  collection: ^1.18.0 # Add this
  http: ^1.2.2 # Add this

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints
  flutter_lints: ^6.0.0

  # For mocking dependencies in tests
  mockito: ^5.4.4

  # Required for generating mock classes
  build_runner: ^2.4.8
