name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  internet_connection_checker: ^1.0.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  shared_preferences: ^2.5.3
  http: ^1.4.0
  socket_io_client: ^2.0.0
  
  flutter_bloc: ^8.1.0
  bloc_test: ^9.1.7
  get_it: ^7.7.0
  go_router: ^16.1.0
  test: ^1.25.15
  mocktail: ^1.0.4
  fake_async: ^1.3.3

flutter:
  assets:
    - lib/assets/images/

  fonts:
    - family: CaveatBrush
      fonts:
        - asset: lib/assets/fonts/CaveatBrush-Regular.ttf

  uses-material-design: true


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
